defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local


# snapshot
save_snapshot: false
load_snap: ""
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 32 #256
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: false
# experiment
experiment: train_rep_0929_sweep
# agent
lr: 1e-4
feature_dim: 50
# lowdim
lowdim: 0
# data
alpha: 0.2


agent:
  _target_: models.Representation
  device: ${device}
  lr: ${lr}
  use_tb: ${use_tb}
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  finetune: 1
  pretrained: 0
  size: 18
  l2weight: 0.01
  smoothweight: 0.0
  structured: true