 
 
 python reward_viz.py hydra/launcher=local hydra/output=local agent.smoothweight=1.0 agent.langweight=1.0 agent.size=34 experiment=vizrew agent.lang_cond=false agent.attntype="sigmoid" agent.finetunelang=0 load_snap="/checkpoint/surajn/drqoutput/train_representation/2021-11-19_12-07-59/18_agent.attntype\=sigmoid\,agent.finetunelang\=0\,agent.lang_cond\=False\,agent.langweight\=1.0\,agent.size\=34\,dataset\=ego4d\,experiment\=train_rep_1119_4/snapshot_920000.pt"
 
 python reward_viz.py hydra/launcher=local hydra/output=local agent.smoothweight=1.0 agent.langweight=1.0 agent.size=34 experiment=vizrew agent.lang_cond=true agent.attntype="modulate" agent.finetunelang=0 load_snap="/checkpoint/surajn/drqoutput/train_representation/2021-11-19_12-07-59/20_agent.attntype\=modulate\,agent.finetunelang\=0\,agent.lang_cond\=True\,agent.langweight\=1.0\,agent.size\=34\,dataset\=ego4d\,experiment\=train_rep_1119_4/snapshot_940000.pt"

 python reward_viz.py hydra/launcher=local hydra/output=local agent.smoothweight=1.0 agent.langweight=1.0 agent.size=34 experiment=vizrew agent.lang_cond=true agent.attntype="sigmoid" agent.finetunelang=0 load_snap="/checkpoint/surajn/drqoutput/train_representation/2021-11-19_12-07-59/22_agent.attntype\=sigmoid\,agent.finetunelang\=0\,agent.lang_cond\=True\,agent.langweight\=1.0\,agent.size\=34\,dataset\=ego4d\,experiment\=train_rep_1119_4/snapshot_840000.pt"

  python reward_viz.py hydra/launcher=local hydra/output=local agent.smoothweight=1.0 agent.langweight=1.0 agent.size=34 experiment=vizrew agent.lang_cond=true agent.attntype="sigmoid" agent.finetunelang=0 load_snap="/checkpoint/surajn/drqoutput/train_representation/2021-11-19_12-07-59/22_agent.attntype\=sigmoid\,agent.finetunelang\=0\,agent.lang_cond\=True\,agent.langweight\=1.0\,agent.size\=34\,dataset\=ego4d\,experiment\=train_rep_1119_4/snapshot_840000.pt"


  python reward_viz.py hydra/launcher=local hydra/output=local agent.smoothweight=1.0 agent.langweight=1.0 agent.size=34 experiment=vizrew agent.lang_cond=false load_snap="/checkpoint/surajn/drqoutput/train_representation/2022-01-04_14-22-31/34_agent.finetunelang\=1\,agent.l1weight\=1e-05\,agent.langtype\=contrastive\,agent.langweight\=1.0\,agent.mask\=False\,agent.size\=50\,batch_size\=16\,dataset\=ego4d\,doaug\=False\,experiment\=rep_0104/snapshot_220000.pt"

  python reward_viz.py hydra/launcher=local hydra/output=local agent.size=50 experiment=vizrew doaug=False agent.langweight=1.0 agent.tcnweight=1.0 agent.lang_cond=false agent.langtype=contrastive dataset=ego4d load_snap="/checkpoint/surajn/drqoutput/train_representation/2021-12-31_15-33-22/5_agent.finetunelang\=1\,agent.l1weight\=0.0001\,agent.langtype\=contrastive\,agent.langweight\=1.0\,agent.mask\=False\,agent.size\=50\,batch_size\=64\,dataset\=ego4d\,experiment\=rep_1231\,num_same\=4/snapshot_420000.pt"