# @package _global_
hydra:
    launcher:
        timeout_min: 4300
        cpus_per_task: 20
        gpus_per_node: 1
        tasks_per_node: 1
        # constraint: volta32gb
        mem_gb: 160
        _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
        submitit_folder: ${hydra.sweep.dir}/.submitit/%j
