defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local


# snapshot
save_snapshot: false
load_snap: ""
# replay buffer
replay_buffer_num_workers: 10
nstep: 3
batch_size: 32 #256
train_steps: 2000000
eval_freq: 20000
num_same: 1
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
# experiment
experiment: train_rep_0929_sweep
# agent
lr: 1e-4
# lowdim
lowdim: 0
# data
alpha: 0.2
dataset: "sthsth"
wandbproject: drq_rep
simclr: false
doaug: "none"


agent:
  _target_: r3m.R3M
  device: ${device}
  lr: ${lr}
  hidden_dim: 1024
  size: 34
  l2weight: 0.00001
  l1weight: 0.00001
  tcnweight: 1.0
  langweight: 0.0
  l2dist: true
  bs: ${batch_size}
